# Generated by Django 5.0.6 on 2024-09-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dailyuseditems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyuseditems',
            name='im',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='Spice/'),
        ),
        migrations.AlterModelTable(
            name='dailyuseditems',
            table='Dailyuseditems_dailyuseditems',
        ),
    ]
