# Generated by Django 5.0.6 on 2024-09-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('im', models.FileField(default=None, max_length=250, null=True, upload_to='Home/')),
                ('pname', models.CharField(max_length=50)),
                ('pdesc', models.TextField(max_length=500)),
                ('pprice', models.IntegerField()),
                ('pquantity', models.IntegerField()),
                ('pgst', models.IntegerField()),
                ('pdc', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Spice',
        ),
    ]
