# Generated by Django 5.0.6 on 2024-09-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cosmetics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cosmetics',
            table='Cosmetics_cosmetics',
        ),
    ]
