# Generated by Django 5.0.6 on 2024-08-27 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contactus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='Name',
            new_name='name',
        ),
    ]
